# Generated by Django 5.2.15 on 2026-06-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Непустой = вид открыт по публичной ссылке без входа (read-only).', max_length=43, verbose_name='Токен публичной ссылки'),
        ),
    ]
