# Generated by Django 5.2.15 on 2026-07-01 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedview_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('region', 'Регион'), ('metric', 'Показатель')], max_length=16, verbose_name='Тип')),
                ('ref', models.CharField(help_text='ОКАТО региона или ID показателя.', max_length=64, verbose_name='Ссылка')),
                ('label', models.CharField(blank=True, default='', max_length=300, verbose_name='Подпись')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'ref'), name='uniq_favorite_user_kind_ref')],
            },
        ),
    ]
