# Generated by Django 5.2.15 on 2026-07-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('okatos', models.JSONField(default=list, verbose_name='Регионы (ОКАТО)')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Набор сравнения',
                'verbose_name_plural': 'Наборы сравнения',
                'ordering': ['-created', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='uniq_comparisonset_user_name')],
            },
        ),
    ]
