# Generated by Django 5.2.15 on 2026-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comparisonset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_measure',
            field=models.CharField(choices=[('cluster', 'Тип (кластер)'), ('index', 'Индекс развития')], default='cluster', max_length=16, verbose_name='Мера карты по умолчанию'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_scheme',
            field=models.CharField(choices=[('equal', 'Равные веса'), ('pca', 'PCA'), ('expert', 'Экспертные')], default='equal', max_length=16, verbose_name='Схема весов по умолчанию'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год по умолчанию'),
        ),
    ]
