# Generated by Django 5.2.15 on 2026-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_default_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Личный ключ для доступа к API (заголовок Authorization: Token …).', max_length=43, verbose_name='Токен API'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_region_okato',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Последний открытый регион (ОКАТО)'),
        ),
    ]
