# Generated by Django 6.0.6 on 2026-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_api_token_userprofile_last_region_okato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256-хеш личного ключа доступа к API (заголовок Authorization: Token …).', max_length=64, verbose_name='Хеш токена API'),
        ),
    ]
