# Generated by Django 5.2.16 on 2026-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='fmt',
            field=models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)'), ('pdf', 'PDF (.pdf)')], max_length=8, verbose_name='Формат'),
        ),
    ]
